version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: todo-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-dev123}
    volumes:
      - redis-dev-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - todo-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  redis-dev-data:
    driver: local

networks:
  todo-dev-network:
    driver: bridge